// Code generated by goctl. DO NOT EDIT.
package types

type GETSSHInfoReq struct {
	Page int64 `json:"page"`
	PageItemsNum int64 `json:"pageItemsNum"`
}

type GETSSHInfoResp struct {
	Id       int64  `json:"id"` // Primary Key
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type AddSSHInfoReq struct {
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type AddSSHInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type UpdateSSHInfoReq struct {
	Id       int64  `json:"id"` // Primary Key
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type UpdateSSHInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type DELETESSHInfoReq struct {
	Id int64 `json:"id"`
}

type DELETESSHInfoResp struct {
	Id int64 `json:"id"`
}

type EchoReq struct {
	Msg string `json:"msg"`
}

type EchoResp struct {
	Msg string `json:"msg"`
}

type SwitchBrandResp struct {
	Id   int64  `json:"id"` // Primary Key
	Name string `json:"name"`
}

type RunCmdReq struct {
	Ip       string `json:"ip"`
	Name     string `json:"name"` // device name
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
}

type RunCmdResp struct {
	Id string `json:"id"` // 返回文件id號, 用它來下載
}

type DownloadCmdResultReq struct {
	Id string `json:"id"`
}

type FileExistReq struct {
	Id string `json:"id"` // 傳入生成的md5 id
}

type FileExistResp struct {
	IsExist bool `json:"isExist"`
}

type GetGroupInfoReq struct {
	Id int64 `json:"id"`
}

type GetGroupInfoResp struct {
	Id    int64            `json:"id"` // Primary Key
	Name  string           `json:"name"`
	Tasks []GETSSHInfoResp `json:"tasks"`
}

type GetGroupName struct {
	Id    int64            `json:"id"` // Primary Key
	Name  string           `json:"name"`
}

type AddGroupInfoReq struct {
	Name string `json:"name"`
}

type AddGroupInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type UpdateGroupInfoReq struct {
	Id   int64  `json:"id"` // Primary Key
	Name string `json:"name"`
}

type UpdateGroupInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type DeleteGroupInfoReq struct {
	Id int64 `json:"id"`
}

type DeleteGroupInfoResp struct {
	Id int64 `json:"id"`
}

type AddGroupTaskReq struct {
	GroupId int64 `json:"groupId"`
	TaskId  int64 `json:"taskId"`
}

type AddGroupTaskResp struct {
	Id int64 `json:"id"`
}

type DeleteGroupTaskReq struct {
	GroupId int64 `json:"groupId"`
	TaskId  int64 `json:"taskId"`
}

type DeleteGroupTaskResp struct {
	Id int64 `json:"id"`
}

type RunGroupTasksReq struct {
	Id int64 `json:"id"`
}

type RunGroupTasksResp struct {
	Id string `json:"id"`
}

type GroupFileExistReq struct {
	Id string `json:"id"`
}

type GroupFileExistResp struct {
	IsExist bool `json:"isExist"`
}

type DownloadGroupFileReq struct {
	Id string `json:"id"`
}
