// Code generated by goctl. DO NOT EDIT.
package types

type GETSSHInfoReq struct {
	Id int64 `json:"id"`
}

type GETSSHInfoResp struct {
	Id       int64  `json:"id"` // Primary Key
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type AddSSHInfoReq struct {
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type AddSSHInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type UpdateSSHInfoReq struct {
	Id       int64  `json:"id"` // Primary Key
	Ip       string `json:"ip"`
	Name     string `json:"name"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
	Desc     string `json:"desc"`   // task desc
}

type UpdateSSHInfoResp struct {
	Id int64 `json:"id"` // Primary Key
}

type DELETESSHInfoReq struct {
	Id int64 `json:"id"`
}

type DELETESSHInfoResp struct {
	Id int64 `json:"id"`
}

type EchoReq struct {
	Msg string `json:"string"`
}

type EchoResp struct {
	Msg string `json:"string"`
}

type SwitchBrandResp struct {
	Id   int64  `json:"id"` // Primary Key
	Name string `json:"name"`
}

type RunCmdReq struct {
	Ip       string `json:"ip"`
	Account  string `json:"account"`
	Password string `json:"password"`
	Brand    string `json:"brand"`  // only for cisco, huawei
	Script   string `json:"script"` // script for task. Statements are separated with ;
}

type RunCmdResp struct {
	Id int64 `json:"id"` // 返回文件id號, 用它來下載
}

type DownloadCmdResultReq struct {
	Id int64 `json:"id"`
}
